const fs = require('fs')

const track = {
    number: 1,
    title: "Invocation of Apocalyptic Evil"
}

const album = {
    title: "Valley of the Damned",
    year: 2003,
    songs: track
}

fs.writeFileSync('jsonData.json', JSON.stringify(album))

//     ("Valley of the Damned", 2003, (
//         (1, "Invocation of Apocalyptic Evil"),
//         (2, "Valley of the Damned"),
//         (3, "Black Fire"),
//         (4, "Black Winter Nights"),
//         (5, "Starfire"),
//         (6, "Disciples of Babylon"),
//         (7, "Revelations"),
//         (8, "Evening Star"),
//         (9, "Heart of a Dragon"),
//     )),
//     ("Sonic Firestorm", 2004, (
//         (1, "My Spirit Will Go On"),
//         (2, "Fury of the Storm"),
//         (3, "Fields of Despair"),
//         (4, "Dawn Over a new World"),
//         (5, "Above the Winter Moonlight"),
//         (6, "Soldiers of the Wasteland"),
//         (7, "Prepare for War"),
//         (8, "Once in a Lifetime"),
//     )),
//     ("Inhuman Rampage", 2005, (
//         (1, "Through the Fire and Flames"),
//         (2, "Revolution Deathsquad"),
//         (3, "Storming the Burning Fields"),
//         (4, "Operation Ground and Pound"),
//         (5, "Body Breakdown"),
//         (6, "Cry for Eternity"),
//         (7, "The Flame of Youth"),
//         (8, "Trail of Broken Hearts"),
//         (9, "Lost Souls in Endless Time"),
//         (10, "Dragonforce Backstage Rocumentary"),
//     )),
//     ("Ultra Beatdown", 2008, (
//         (1, "Heroes of Our Time"),
//         (2, "The Fire Still Burns"),
//         (3, "Reasons to Live"),
//         (4, "Heartbreak Armageddon"),
//         (5, "The Last Journey Home"),
//         (6, "A Flame for Freedom"),
//         (7, "Inside the Winter Storm"),
//         (8, "The Warrior Inside"),
//     )),
//     ("The Power Within", 2012, (
//         (1, "Holding On"),
//         (2, "Fallen World"),
//         (3, "Cry Thunder"),
//         (4, "Give Me the Night"),
//         (5, "Wings of Liberty"),
//         (6, "Seasons"),
//         (7, "Heart of the Storm"),
//         (8, "Die by the Sword"),
//         (9, "Last Man Stands"),
//         (10, "Seasons (acoustic)"),
//         (11, "Power of the Ninja Sword"),
//     )),
//     ("Maximum Overload", 2014, (
//         (1, "The Game"),
//         (2, "Tomorrow's Kings"),
//         (3, "No More"),
//         (4, "Three Hammers"),
//         (5, "Symphony of the Night"),
//         (6, "The Sun is Dead"),
//         (7, "Defenders"),
//         (8, "Extraction Zone"),
//         (9, "City of Gold"),
//         (10, "Ring of Fire"),
//         (11, "Power and Glory"),
//         (12, "You're Not Alone"),
//         (13, "Chemical Interference"),
//         (14, "Fight to be Free"),
//         (15, "Galactic Astro Domination"),
//     )),
//     ("Reaching into Infinity", 2017, (
//         (1, "Reaching into Infinity"),
//         (2, "Ashes of the Dawn"),
//         (3, "Judgement Day"),
//         (4, "Astral Empire"),
//         (5, "Curse of Darkness"),
//         (6, "Silence"),
//         (7, "Midnight Madness"),
//         (8, "WAR!"),
//         (9, "Land of Shattered Dreams"),
//         (10, "The Edge of the World"),
//         (11, "Our Final Stand"),
//         (12, "Gloria"),
//     )),
//     ("Extreme Power Metal", 2019, (
//         (1, "Highway to Oblivion"),
//         (2, "Cosmic Power of the Infinite Shred Machine"),
//         (3, "The Last Dragonborn"),
//         (4, "Heart Demolition"),
//         (5, "Troopers of the Stars"),
//         (6, "Razorblade Meltdown"),
//         (7, "Strangers"),
//         (8, "In a Skyforged Dream"),
//         (9, "Remembrance Day"),
//         (10, "My Heart Will Go On"),
//         (11, "Behind the Mirror of Death"),
//     )),
// ]